version: "3.9"

services:
  scheduler:
    build: scheduler/.
    ports:
      - "81:80"
    profiles:
      - scheduler_service
  storefront: 
    build: storefront/.
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - database
    profiles:
      - storefront_service
  database: 
    image: "mysql"
    env_file:
      - ./mysql/env_vars
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d:ro
      - kineteco:/var/lib/mysql
    profiles:
    - storefront_service
    - scheduler_service
volumes:
  kineteco: 